### ISSUE TITLE
Backup file is not truncated, has trailing garbage

### ISSUE THREAD

**Issue by linusnielsen** [openintents/safe#16]
I have an issue with the (auto)backup feature. If I have deleted some passwords since the last backup, the resulting backup file is not truncated, but contains the remains of the last backup file, after the closing </OISafe> tag.
My theory is that the FileOutputStream isn't closed after writing the file, and then it isn't properly truncated. Adding a str.close() in backupDatabase() should probably do the trick.

**Comment by friedger** [comment]
Should be fixed by https://github.com/openintents/safe/commit/cc00c57088a316b8a7bc9ab091f5ab88711dbbac

Have you tried to build from source?

**Comment by linusnielsen** [comment]
Ooops. My bad. I cloned the repo but didn't spot the fix. I haven't built from source, since I don't have a dev environment set up. I'm not an Android developer.

**Comment by friedger** [comment]
No worries, I will update the app in Google Play.

**Comment by linusnielsen** [comment]
Thanks!
