### ISSUE TITLE
New version intro gives white-on-white text

### ISSUE THREAD

**Issue by SyntaxPolice** [openintents/safe#24]
Greetings! FYI I'm one of the original authors of various aspects of this app :)

I received an update and it notified me with a screen that had white / grey text on a white background and so I couldn't read it. Also now the color scheme seems to have changed, so that might be related.

**Comment by friedger** [comment]
I don't know when this was fixed, but we have now material design and this should be fixed. Beta available at https://play.google.com/apps/testing/org.openintents.safe
