### ISSUE TITLE
User Suggestion: Adding pics/files to the OI safe

### ISSUE THREAD

**Issue by mtris** [openintents/safe#30]
Dear Open Intents Team: You did a great job designing each app Ive tried. I hope there are fure releases of any/all of your apps.
My user suggestion is: To have the ability to add files/pics to OI safe entries. When I keep bank into or contact info locked up, it would be convenient to attach [a contact pic, pic of a bank card etc.] along with the entry.
Thank you for your consideration, and hope you enjoy a happy and safe New Year 🎉

**Comment by WrongBit** [comment]
+1 to the suggestion. Ideally I don't want to jump on "safes" - I wanna click in File Manager any file and in popup select: "encrypt" or "Decrypt and open in associated app". We are users and keep files IN FOLDERS, not in safes. To be useful, encryption must be transparently integrated into Android.

**Comment by friedger** [comment]
We used to have an app for exactly that, an image gallery with content providers and encryption via OI Safe

![Screenshot from 2022-01-12 11-31-09](https://user-images.githubusercontent.com/1449049/149123712-ce2955a8-095f-48ee-acda-c8457ad67296.png)

However, there is so much that can go wrong that we can't provide customer support for these kind of applications. Therefore, we won't publish an application like that again.
