### ISSUE TITLE
github code search misses openintents/safe

### ISSUE THREAD

**Issue by anaran** [openintents/safe#6]
Hello Friedger,

I just noticed that a github code search for

Advanced Search
`[repo:openintents/safe license]` Search

Search for
`[Code]`

Search Language
`[Any Language]`

comes up empty.

I made sure I didn't make an obvious mistake by successfully searching another project:

Advanced Search [repo:mishoo/ymacs license](https://github.com/search?q=repo%3Amishoo%2Fymacs+license&repo=&langOverride=&start_value=1&type=Code&language=)

Friedger, do you know what the problem might be?

Thanks for the great OI Safe app!

Best regards
anaran

**Comment by friedger** [comment]
fixed by now
