### ISSUE TITLE
Crash if clicked quickly

### ISSUE THREAD

**Issue by HenryHu** [openintents/safe#8]
I've just encountered this crash and I'm able to repeat this process, on Nexus 7, OI Safe 1.4.1:
1. start OI Safe
2. click Accept
3. click Continue
4. fill in password and confirm password, such as 'test'
5. press Menu, or click the "Menu" button in the action bar
6. select About
7. select "Market Download"
8. click "Continue" as soon as the button is pressed
9. It may crash

I tried this repeatedly and the chance is greater than 1/10
The stack trace looks like this:
E/AndroidRuntime( 3007): FATAL EXCEPTION: main
E/AndroidRuntime( 3007): java.lang.NullPointerException
E/AndroidRuntime( 3007):    at org.openintents.safe.AskPassword.handleContinue(AskPassword.java:283)
E/AndroidRuntime( 3007):    at org.openintents.safe.AskPassword.access$100(AskPassword.java:59)
E/AndroidRuntime( 3007):    at org.openintents.safe.AskPassword$5.onClick(AskPassword.java:229)
E/AndroidRuntime( 3007):    at android.view.View.performClick(View.java:4202)
E/AndroidRuntime( 3007):    at android.view.View$PerformClick.run(View.java:17340)
E/AndroidRuntime( 3007):    at android.os.Handler.handleCallback(Handler.java:725)
E/AndroidRuntime( 3007):    at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 3007):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 3007):    at android.app.ActivityThread.main(ActivityThread.java:5039)
E/AndroidRuntime( 3007):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3007):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 3007):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime( 3007):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
E/AndroidRuntime( 3007):    at dalvik.system.NativeStart.main(Native Method)

The problem seems to be caused by dbHelper, which seems to be null in this case. It can only be cleared in onPause().
Maybe this bug seems to be unimportant, since it only happens in rare cases. However, this bug means that event handlers may be called after onPause(). This is reasonable since that before onStop(), your activity is still visible. In other cases, onPause() may be called for other reasons, and it may make the bug easier to happen. So a better place to clear dbHelper may be in onStop().

**Comment by friedger** [comment]
Integration with About has been removed.
